add docker install

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -44,6 +44,14 @@ jobs:
           key: ${{ secrets.AZURE_VM_SSH_KEY }}
           port: 22
           script: |
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found. Installing..."
+                curl -fsSL https://get.docker.com -o get-docker.sh
+                sudo sh get-docker.sh
+                sudo usermod -aG docker $USER
+            fi
+            
             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-tutorial:latest
             sudo docker stop ci-cd-tutorial || true
             sudo docker rm ci-cd-tutorial || true
